export default {
  SCENES: {
    MENU: "MENU",
    SESSIONHOSTSETTINGS: "SESSIONHOSTSETTINGS",
    SESSIONBROWSER: "SESSIONBROWSER",
    LOAD: "LOAD",
    GAME: "GAME",
    RESULT: "RESULT",
    SESSIONLOBBY: "SESSIONLOBBY",
    SPAWNSELECTSCENE: "SPAWNSELECT",
    HUD_SCORE: "SCOREHUD",
    TUTORIAL: "TUTORIAL",
  },
  GAMEEVENTS: {
    SOLDIER_CREATED: "SC",
    SOLDIER_KILLED: "SK",
    SOLDIER_UPDATED: "SU",

    SOLDIER_SELECTED: "SS",
    SOLDIER_UNSELECTED: "SUS",

    CAPTURE_FLAG_SELECTED: "CFS",
    CAPTURE_FLAG_UNSELECTED: "CFUS",

    RIGHT_CLICK: "RC",
    SOLDIER_MOVE_REQUESTED: "SMR",
    DELETE_SELECTED_OBJECTS: "DELSLCTDOBJS",
    CREATE_CAPTURE_FLAG_BUTTON_CLICKED: "CFLGBTNCLICKED",
  },
  WIDTH: 3500,
  HEIGHT: 1500,
};
