module.exports = {
    MAX_STEER_FORCE: 5,
    MAX_REPEL_FORCE: 20,

    MAX_ACCELERATION: 1.2,
    DESIRED_DIST_FROM_TARGET: 50,
    NEARBY_SEARCH_RADI: 150,
    DESIRED_SEPERATION_DIST: 90, //to initiate repulsion force
    MAX_TARGETPOS_OVERLAP_DIST: 40,
}