export default {
  MAX_STEER_FORCE: 5,
  MAX_REPEL_FORCE: 9,
  DESIRED_DIST_FROM_TARGET: 50,
  ACCEPTABLE_DIST_FROM_EXPECTED_POS: 2,
  NEARBY_SEARCH_RADI: 150,
  ENEMY_SEARCH_RADIUS: 200,
  DESIRED_SEPERATION_DIST: 20, //to initiate repulsion force
  MAX_TARGETPOS_OVERLAP_DIST: 40,
};
