module.exports = {
    MAX_FORCE: 12,

    MAX_STEER_FORCE: 3,
    MAX_REPEL_FORCE: 20,

    MAX_ACCELERATION: 3,
    DESIRED_DIST_FROM_TARGET: 90,
    NEARBY_SEARCH_RADI: 100,
    DESIRED_SEPERATION_DIST: 90,
}